# Generated by Django 4.2.26 on 2025-11-28 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organization.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "industry",
                    models.IntegerField(
                        choices=[
                            (1, "IT SERVICES"),
                            (2, "Product Based"),
                            (3, "Finance"),
                            (4, "Sport"),
                            (5, "Healthcare"),
                            (6, "Automobile"),
                            (7, "Non-Profit"),
                            (8, "Public-Sector"),
                            (9, "Retail"),
                            (10, "Hospitality"),
                            (11, "Business"),
                            (12, "Others"),
                        ]
                    ),
                ),
                ("headquarter_location", models.CharField(max_length=100)),
                ("about", models.TextField()),
                (
                    "employee_size",
                    models.IntegerField(
                        choices=[
                            (1, "1-10"),
                            (2, "10-100"),
                            (3, "100-500"),
                            (4, "500-1000"),
                            (5, "1000+"),
                        ]
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, unique=True)),
                ("linkedin_url", models.URLField(blank=True, null=True, unique=True)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "root_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_root_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invite_code",
                    models.CharField(
                        default=organization.models.create_organization_invite,
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["invite_code"], name="organizatio_invite__b6caa4_idx"
                    ),
                    models.Index(fields=["email"], name="organizatio_email_afcec5_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["industry"], name="organizatio_industr_ccfa43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["employee_size"], name="organizatio_employe_c37774_idx"
            ),
        ),
    ]
