# Generated by Django 4.2.26 on 2025-11-28 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_file", models.URLField(blank=True, max_length=500, null=True)),
                ("video_pitch", models.URLField(blank=True, max_length=500, null=True)),
                ("resume_data", models.JSONField(blank=True, null=True)),
                (
                    "parsing_status",
                    models.CharField(
                        choices=[
                            ("not_parsed", "Not Parsed"),
                            ("parsing", "Parsing In Progress"),
                            ("parsed", "Parsed Successfully"),
                            ("failed", "Parsing Failed"),
                        ],
                        default="not_parsed",
                        max_length=20,
                    ),
                ),
                ("willing_to_relocate", models.BooleanField(default=True)),
                ("employment_type_preferences", models.JSONField(default=list)),
                ("work_mode_preferences", models.JSONField(default=list)),
                ("has_workvisa", models.BooleanField(default=False)),
                ("disability_categories", models.JSONField(default=list)),
                (
                    "accommodation_needs",
                    models.CharField(
                        choices=[
                            ("YES", "YES"),
                            ("NO", "NO"),
                            ("PREFER_TO_DISCUSS_LATER", "PREFER_TO_DISCUSS_LATER"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "disclosure_preference",
                    models.CharField(
                        choices=[
                            ("DURING_APPLICATION", "DURING_APPLICATION"),
                            ("DURING_INTERVIEW", "DURING_INTERVIEW"),
                            ("AFTER_JOB_OFFER", "AFTER_JOB_OFFER"),
                            ("AFTER_STARTING_WORK", "AFTER_STARTING_WORK"),
                            ("NOT_APPLICABLE", "NOT_APPLICABLE"),
                        ],
                        max_length=100,
                    ),
                ),
                ("workplace_accommodations", models.JSONField(default=list)),
                (
                    "expected_salary_range",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["organization", "id"],
            },
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                ("section", models.TextField(blank=True, null=True)),
                ("selected_text", models.TextField(blank=True, null=True)),
                ("context", models.JSONField(blank=True, null=True)),
                ("note", models.CharField(max_length=100)),
                ("note_file", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="candidates.candidateprofile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="candidateprofile",
            index=models.Index(fields=["slug"], name="candidates__slug_98b3e9_idx"),
        ),
        migrations.AddIndex(
            model_name="candidateprofile",
            index=models.Index(
                fields=["parsing_status"], name="candidates__parsing_6a43e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidateprofile",
            index=models.Index(
                fields=["is_available"], name="candidates__is_avai_93e9e2_idx"
            ),
        ),
    ]
