# Generated by Django 4.2.26 on 2025-11-28 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Skills",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("job_desc", models.TextField()),
                (
                    "workplace_type",
                    models.IntegerField(
                        choices=[(1, "Hybrid"), (2, "On-Site"), (3, "Remote")]
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "job_type",
                    models.IntegerField(
                        choices=[
                            (1, "Full-time"),
                            (2, "Part-time"),
                            (3, "Contract"),
                            (4, "Temporary"),
                            (5, "Other"),
                            (6, "Volunteer"),
                            (7, "Internship"),
                        ]
                    ),
                ),
                ("estimated_salary", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visa_required", models.BooleanField(default=False)),
                ("candidate_ranking_data", models.JSONField(blank=True, null=True)),
                (
                    "ranking_status",
                    models.CharField(
                        choices=[
                            ("not_ranked", "Not Ranked"),
                            ("ranking", "Ranking in Progress"),
                            ("ranked", "Ranked Successfully"),
                            ("failed", "Ranking Failed"),
                        ],
                        default="not_ranked",
                        max_length=20,
                    ),
                ),
                (
                    "ranking_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
                ("skills", models.ManyToManyField(to="main.skills")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"],
                        name="main_jobpos_organiz_6a0da8_idx",
                    ),
                    models.Index(
                        fields=["ranking_status"], name="main_jobpos_ranking_b12969_idx"
                    ),
                    models.Index(
                        fields=["visa_required"], name="main_jobpos_visa_re_594c40_idx"
                    ),
                ],
            },
        ),
    ]
