# Generated by Django 4.2.26 on 2025-12-19 15:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(blank=True, null=True)),
                (
                    "candidate_slug",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("recruiter", "Recruiter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chat_sessions",
                "indexes": [
                    models.Index(
                        fields=["mode", "created_at"],
                        name="chat_sessio_mode_fdf059_idx",
                    ),
                    models.Index(
                        fields=["candidate_slug"], name="chat_sessio_candida_02a5d6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("user", "User"),
                            ("assistant", "Assistant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        db_column="session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="main.chatsession",
                    ),
                ),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"],
                        name="chat_messag_session_597c4e_idx",
                    ),
                    models.Index(fields=["role"], name="chat_messag_role_ddd811_idx"),
                ],
            },
        ),
    ]
